name: Publish

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Run ESLint check
        run: pnpm lint:ci

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Run Prettier check
        run: pnpm format:ci

  release:
    name: Publish
    runs-on: ubuntu-latest
    needs: [eslint, prettier]
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Publish
        run: pnpm semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_BOT_PAT }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN_ELEVATED }}
          GIT_AUTHOR_NAME: ${{ secrets.RELEASE_BOT_NAME }}
          GIT_AUTHOR_EMAIL: ${{ secrets.RELEASE_BOT_EMAIL }}
          GIT_COMMITTER_NAME: ${{ secrets.RELEASE_BOT_NAME }}
          GIT_COMMITTER_EMAIL: ${{ secrets.RELEASE_BOT_EMAIL }}
